#!/usr/bin/env node

const fs = require("fs")

const lang = (locale) => {
	const sp = locale.split("-")
	return { first: sp[0], second: sp[1] ?? "", file: locale }
}

const main = (list) => {
	const out = ["// DO NOT EDIT THIS FILE; it is generated by locales.js",
		"", "pub const all: List(#(String, String, List(#(String, String)))) = ["]
	for (let i = 0; i < list.length; i++) {
		const language = lang(list[i])
		const translations = JSON.parse(fs.readFileSync("./locales/" + language.file + ".json"))
		out.push('   #("' + language.first + '", "' + language.second + '", [\n' +
			translations.sort((a, b) => a.key.localeCompare(b.key)).map(
				it => '      #("' + it.key + '", "' + it.value + '"),').join('\n') +
			'\n   ]),')
	}
	out.push("]")
	fs.writeFileSync("./src/msgs.gleam", out.join("\n") + "\n")
}

main(["bg-BG"])
